import { engineName } from "@/lib/resumeEngine";
import { ResumeReport } from "@/lib/report-schema";

type PdfLine = {
  text: string;
  size: number;
  gapAfter?: number;
};

const pageWidth = 612;
const pageHeight = 792;
const marginX = 56;
const topY = 736;
const bottomY = 56;
const contentWidth = pageWidth - marginX * 2;

export function reportToPdf(report: ResumeReport) {
  const lines = buildReportLines(report);
  const pages = paginate(lines);
  const objects: string[] = [];

  objects[1] = "<< /Type /Catalog /Pages 2 0 R >>";
  objects[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";

  const pageObjectIds: number[] = [];

  for (const pageLines of pages) {
    const pageObjectId = objects.length;
    const contentObjectId = pageObjectId + 1;
    pageObjectIds.push(pageObjectId);

    objects[pageObjectId] =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentObjectId} 0 R >>`;
    const stream = renderPage(pageLines);
    objects[contentObjectId] = `<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`;
  }

  objects[2] = `<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageObjectIds.length} >>`;

  return Buffer.from(writePdf(objects), "utf8");
}

function buildReportLines(report: ResumeReport): PdfLine[] {
  const premiumReport = report.paidReport.premiumReport;

  return [
    heading("Recruiter Mind Report", 24),
    body(`Generated by ${engineName} v${report.engineVersion}`),
    body("Resume Score by ScoreLab"),
    spacer(),
    heading("Scores", 16),
    body(`Overall Resume Score: ${report.overallScore}/100`),
    body(`ATS Compatibility Score: ${report.atsCompatibilityScore}/100`),
    body(`Interview Readiness Score: ${report.interviewReadinessScore}/100`),
    body(`Recruiter Attention Score: ${report.recruiterAttentionScore}/100`),
    body(`Interview Readiness Level: ${report.interviewReadinessLevel}`),
    spacer(),
    heading("Executive Summary", 16),
    body(premiumReport.executiveSummary),
    heading("Biggest Opportunity", 16),
    body(premiumReport.biggestOpportunity.whatToImprove),
    body(`Why it matters: ${premiumReport.biggestOpportunity.whyItMatters}`),
    body(`Example: ${premiumReport.biggestOpportunity.example}`),
    body(`Expected impact: ${premiumReport.biggestOpportunity.expectedImpact}`),
    heading("High Impact Improvements", 16),
    ...premiumReport.highImpactImprovements.flatMap((item, index) => [
      body(`${index + 1}. ${item.priorityLevel} priority: ${item.whatWasDetected}`),
      body(`Why it matters: ${item.whyItMatters}`),
      body(`Recruiter impact: ${item.recruiterImpact}`),
      body(`ATS impact: ${item.atsImpact}`),
      body(`Recommended action: ${item.recommendedAction}`),
      body(`Expected benefit: ${item.expectedBenefit}`)
    ]),
    heading("Suggested Rewrite", 16),
    body(`Before: ${premiumReport.suggestedRewrite.before}`),
    body(`After: ${premiumReport.suggestedRewrite.after}`),
    body(`Why this works better: ${premiumReport.suggestedRewrite.whyThisWorksBetter}`),
    spacer(),
    heading("Recruiter First Impression", 16),
    body(premiumReport.recruiterFirstImpression),
    heading("ATS Perspective", 16),
    body(premiumReport.atsPerspective),
    heading("What Stands Out Positively?", 16),
    ...bullets(report.positiveStandouts),
    heading("What May Cause Hesitation?", 16),
    ...bullets(report.hesitationSignals),
    heading("Strengths", 16),
    ...bullets(report.strengths),
    heading("The 5 Most Important Changes Before Applying Again", 16),
    ...report.fiveMostImportantChanges.flatMap((item, index) => [
      body(`${index + 1}. What we noticed: ${item.whatWeNoticed}`),
      body(`Why it matters to recruiters: ${item.whyItMattersToRecruiters}`),
      body(`What to change next: ${item.whatToChangeNext}`)
    ]),
    heading("What to Fix First", 16),
    body(report.whatToFixFirst),
    heading("Why This Matters to Recruiters", 16),
    body(report.whyThisMattersToRecruiters),
    heading("Missing Keywords", 16),
    ...bullets(report.missingKeywords),
    heading("Section-by-section Feedback", 16),
    body(`Summary: ${report.sectionFeedback.summary}`),
    body(`Work Experience: ${report.sectionFeedback.workExperience}`),
    body(`Skills: ${report.sectionFeedback.skills}`),
    body(`Education: ${report.sectionFeedback.education}`),
    body(`Formatting: ${report.sectionFeedback.formatting}`),
    spacer(),
    heading("Rewrite Examples", 16),
    ...bullets(report.rewriteExamples.improvedBulletPoints),
    body(`Improved Professional Summary: ${report.rewriteExamples.improvedProfessionalSummary}`),
    spacer(),
    heading("30-Minute Improvement Plan", 16),
    body(`10 minutes: ${premiumReport.thirtyMinuteImprovementPlan.tenMinutes}`),
    body(`20 minutes: ${premiumReport.thirtyMinuteImprovementPlan.nextTenMinutes}`),
    body(`30 minutes: ${premiumReport.thirtyMinuteImprovementPlan.finalTenMinutes}`),
    heading("Long-Term Career Signal", 16),
    body(premiumReport.longTermCareerSignal),
    heading("Encouraging Closing Note", 16),
    body(report.encouragingClosingNote),
    spacer(),
    heading("Disclaimer", 16),
    body(report.disclaimer),
    spacer(),
    body(`Generated by ${engineName} v${report.engineVersion}`)
  ];
}

function paginate(lines: PdfLine[]) {
  const pages: PdfLine[][] = [];
  let current: PdfLine[] = [];
  let y = topY;

  for (const line of lines.flatMap(wrapLine)) {
    const lineHeight = line.size + (line.gapAfter || 5);
    if (y - lineHeight < bottomY && current.length > 0) {
      pages.push(current);
      current = [];
      y = topY;
    }

    current.push(line);
    y -= lineHeight;
  }

  if (current.length > 0) pages.push(current);
  return pages;
}

function renderPage(lines: PdfLine[]) {
  let y = topY;
  const commands = ["0.08 0.10 0.16 rg"];

  for (const line of lines) {
    commands.push(`BT /F1 ${line.size} Tf ${marginX} ${y} Td (${escapePdfText(line.text)}) Tj ET`);
    y -= line.size + (line.gapAfter || 5);
  }

  return commands.join("\n");
}

function writePdf(objects: string[]) {
  const chunks = ["%PDF-1.4\n"];
  const offsets = [0];

  for (let id = 1; id < objects.length; id += 1) {
    offsets[id] = Buffer.byteLength(chunks.join(""), "utf8");
    chunks.push(`${id} 0 obj\n${objects[id]}\nendobj\n`);
  }

  const xrefOffset = Buffer.byteLength(chunks.join(""), "utf8");
  chunks.push(`xref\n0 ${objects.length}\n0000000000 65535 f \n`);

  for (let id = 1; id < objects.length; id += 1) {
    chunks.push(`${String(offsets[id]).padStart(10, "0")} 00000 n \n`);
  }

  chunks.push(`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`);
  return chunks.join("");
}

function wrapLine(line: PdfLine): PdfLine[] {
  if (!line.text) return [line];

  const maxChars = Math.max(36, Math.floor(contentWidth / (line.size * 0.52)));
  const words = line.text.split(/\s+/);
  const wrapped: PdfLine[] = [];
  let current = "";

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (candidate.length > maxChars && current) {
      wrapped.push({ ...line, text: current, gapAfter: 3 });
      current = word;
    } else {
      current = candidate;
    }
  }

  if (current) wrapped.push({ ...line, text: current });
  return wrapped;
}

function heading(text: string, size: number): PdfLine {
  return { text, size, gapAfter: 10 };
}

function body(text: string): PdfLine {
  return { text, size: 10, gapAfter: 6 };
}

function spacer(): PdfLine {
  return { text: "", size: 6, gapAfter: 8 };
}

function bullets(items: string[]) {
  return items.map((item) => body(`- ${item}`));
}

function numbered(items: string[]) {
  return items.map((item, index) => body(`${index + 1}. ${item}`));
}

function escapePdfText(text: string) {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}
