import { engineName } from "@/lib/resumeEngine";
import { ResumeReport } from "@/lib/report-schema";

export function reportToMarkdown(report: ResumeReport) {
  const premiumReport = report.paidReport.premiumReport;

  return `# Recruiter Mind Report

## Scores

- Engine Version: ${report.engineVersion}
- Overall Resume Score: ${report.overallScore}/100
- ATS Compatibility Score: ${report.atsCompatibilityScore}/100
- Interview Readiness Score: ${report.interviewReadinessScore}/100
- Recruiter Attention Score: ${report.recruiterAttentionScore}/100
- Interview Readiness Level: ${report.interviewReadinessLevel}

## Top Issues

${report.topIssues.map((item, index) => `${index + 1}. ${item}`).join("\n")}

## Executive Summary

${premiumReport.executiveSummary}

## Biggest Opportunity

${premiumReport.biggestOpportunity.whatToImprove}

- Why it matters: ${premiumReport.biggestOpportunity.whyItMatters}
- Example: ${premiumReport.biggestOpportunity.example}
- Expected impact: ${premiumReport.biggestOpportunity.expectedImpact}

## High Impact Improvements

${premiumReport.highImpactImprovements
  .map(
    (item, index) =>
      `${index + 1}. ${item.priorityLevel} priority\n   What was detected: ${item.whatWasDetected}\n   Why it matters: ${item.whyItMatters}\n   Recruiter impact: ${item.recruiterImpact}\n   ATS impact: ${item.atsImpact}\n   Recommended action: ${item.recommendedAction}\n   Expected benefit: ${item.expectedBenefit}`
  )
  .join("\n")}

## Suggested Rewrite

Before:
${premiumReport.suggestedRewrite.before}

After:
${premiumReport.suggestedRewrite.after}

Why this works better:
${premiumReport.suggestedRewrite.whyThisWorksBetter}

## Recruiter First Impression

${premiumReport.recruiterFirstImpression}

## ATS Perspective

${premiumReport.atsPerspective}

## What Stands Out Positively?

${report.positiveStandouts.map((item) => `- ${item}`).join("\n")}

## What May Cause Hesitation?

${report.hesitationSignals.map((item) => `- ${item}`).join("\n")}

## Strengths
${report.strengths.map((item) => `- ${item}`).join("\n")}

## Weaknesses

${report.weaknesses.map((item) => `- ${item}`).join("\n")}

## Missing Keywords

${report.missingKeywords.map((item) => `- ${item}`).join("\n")}

## The 5 Most Important Changes Before Applying Again

${report.fiveMostImportantChanges
  .map(
    (item, index) =>
      `${index + 1}. What we noticed: ${item.whatWeNoticed}\n   Why it matters to recruiters: ${item.whyItMattersToRecruiters}\n   What to change next: ${item.whatToChangeNext}`
  )
  .join("\n")}

## What to Fix First

${report.whatToFixFirst}

## Why This Matters to Recruiters

${report.whyThisMattersToRecruiters}

## Section-by-section Feedback

### Summary
${report.sectionFeedback.summary}

### Work Experience
${report.sectionFeedback.workExperience}

### Skills
${report.sectionFeedback.skills}

### Education
${report.sectionFeedback.education}

### Formatting
${report.sectionFeedback.formatting}

## Rewrite Examples

### Improved Bullet Points
${report.rewriteExamples.improvedBulletPoints.map((item) => `- ${item}`).join("\n")}

### Improved Professional Summary
${report.rewriteExamples.improvedProfessionalSummary}

## 30-Minute Improvement Plan

1. ${premiumReport.thirtyMinuteImprovementPlan.tenMinutes}
2. ${premiumReport.thirtyMinuteImprovementPlan.nextTenMinutes}
3. ${premiumReport.thirtyMinuteImprovementPlan.finalTenMinutes}

## Long-Term Career Signal

${premiumReport.longTermCareerSignal}

## Encouraging Closing Note

${report.encouragingClosingNote}

## Disclaimer

${report.disclaimer}

Generated by ${engineName} v${report.engineVersion}
`;
}
