import { engineName } from "@/lib/resumeEngine";
import { ResumeReport } from "@/lib/report-schema";

export function reportToMarkdown(report: ResumeReport) {
  return `# Recruiter Mind Report

## Scores

- Engine Version: ${report.engineVersion}
- Overall Resume Score: ${report.overallScore}/100
- ATS Compatibility Score: ${report.atsCompatibilityScore}/100
- Interview Readiness Score: ${report.interviewReadinessScore}/100
- Recruiter Attention Score: ${report.recruiterAttentionScore}/100
- Interview Readiness Level: ${report.interviewReadinessLevel}

## Top Issues

${report.topIssues.map((item, index) => `${index + 1}. ${item}`).join("\n")}

## Recruiter First Impression

${report.recruiterFirstImpression}

## Would a Recruiter Keep Reading?

${report.wouldRecruiterKeepReading}

## What Stands Out Positively?

${report.positiveStandouts.map((item) => `- ${item}`).join("\n")}

## What May Cause Hesitation?

${report.hesitationSignals.map((item) => `- ${item}`).join("\n")}

## Strengths
${report.strengths.map((item) => `- ${item}`).join("\n")}

## Weaknesses

${report.weaknesses.map((item) => `- ${item}`).join("\n")}

## Missing Keywords

${report.missingKeywords.map((item) => `- ${item}`).join("\n")}

## The 5 Most Important Changes Before Applying Again

${report.fiveMostImportantChanges
  .map(
    (item, index) =>
      `${index + 1}. What we noticed: ${item.whatWeNoticed}\n   Why it matters to recruiters: ${item.whyItMattersToRecruiters}\n   What to change next: ${item.whatToChangeNext}`
  )
  .join("\n")}

## What to Fix First

${report.whatToFixFirst}

## Why This Matters to Recruiters

${report.whyThisMattersToRecruiters}

## Section-by-section Feedback

### Summary
${report.sectionFeedback.summary}

### Work Experience
${report.sectionFeedback.workExperience}

### Skills
${report.sectionFeedback.skills}

### Education
${report.sectionFeedback.education}

### Formatting
${report.sectionFeedback.formatting}

## Rewrite Examples

### Improved Bullet Points
${report.rewriteExamples.improvedBulletPoints.map((item) => `- ${item}`).join("\n")}

### Improved Professional Summary
${report.rewriteExamples.improvedProfessionalSummary}

## Final Action Plan

${report.finalActionPlan.map((item, index) => `${index + 1}. ${item}`).join("\n")}

## Encouraging Closing Note

${report.encouragingClosingNote}

## Disclaimer

${report.disclaimer}

Generated by ${engineName} v${report.engineVersion}
`;
}
