import { gradeCategory } from "./resumeRules";
import {
  CategoryBreakdown,
  ResumeCategoryBreakdown,
  ResumeFreePreview,
  ResumePaidReport,
  ResumeReport,
  ScoringCategoryKey
} from "./resumeTypes";
import { engineVersion } from "./resumeVersion";

const categoryKeys: ScoringCategoryKey[] = [
  "atsCompatibility",
  "clarityStructure",
  "impactAchievements",
  "keywordRelevance",
  "professionalPresentation"
];

export function buildFreePreview(report: ResumeReport): ResumeFreePreview {
  return {
    overallScore: Math.round(report.overallScore),
    atsReadinessScore: Math.round(report.atsCompatibilityScore),
    interviewReadinessLevel: report.interviewReadinessLevel,
    top3Issues: buildPrecheckAwareTopIssues(report)
  };
}

export function buildPaidReport(report: ResumeReport): ResumePaidReport {
  return {
    categoryBreakdown: report.categoryBreakdown,
    detailedExplanation: report.summaryDiagnosis,
    sectionFeedback: report.sectionFeedback,
    top10ImprovementPriorities: buildTop10Priorities(report),
    missingKeywords: report.missingKeywords,
    rewriteExamples: report.rewriteExamples,
    finalActionPlan: report.finalActionPlan,
    triggeredRules: report.triggeredRules,
    resumeEnginePreCheck: buildResumeEnginePreCheck(report)
  };
}

export function buildDownloadableReportData(report: ResumeReport) {
  return {
    engineVersion: report.engineVersion,
    generatedBy: `Generated by Resume Engine v${report.engineVersion}`,
    freePreview: report.freePreview,
    paidReport: report.paidReport,
    disclaimer: report.disclaimer
  };
}

export function normalizeResumeReport(report: ResumeReport): ResumeReport {
  const categoryBreakdown = calibrateCategoryBreakdown(normalizeCategoryBreakdown(report.categoryBreakdown), report);
  const baseCategoryScores = {
    atsCompatibilityScore: categoryBreakdown.atsCompatibility.score * 5,
    clarityStructureScore: categoryBreakdown.clarityStructure.score * 5,
    impactAchievementsScore: categoryBreakdown.impactAchievements.score * 5,
    keywordRelevanceScore: categoryBreakdown.keywordRelevance.score * 5,
    professionalPresentationScore: categoryBreakdown.professionalPresentation.score * 5
  };
  const categoryScores = {
    ...baseCategoryScores,
    atsCompatibilityScore: Math.round(
      baseCategoryScores.atsCompatibilityScore * 0.55 +
      baseCategoryScores.clarityStructureScore * 0.15 +
      baseCategoryScores.impactAchievementsScore * 0.15 +
      baseCategoryScores.keywordRelevanceScore * 0.15
    )
  };
  const overallScore = categoryKeys.reduce((sum, key) => sum + categoryBreakdown[key].score, 0);
  const interviewReadinessScore = clampScore(
    Math.round(
      overallScore * 0.65 +
      categoryScores.impactAchievementsScore * 0.2 +
      categoryScores.clarityStructureScore * 0.15
    ),
    0,
    100
  );
  const recruiterAttentionScore = clampScore(
    Math.round(
      categoryScores.clarityStructureScore * 0.35 +
      categoryScores.impactAchievementsScore * 0.4 +
      categoryScores.professionalPresentationScore * 0.25
    ),
    0,
    100
  );

  const normalized: ResumeReport = {
    ...report,
    engineVersion,
    categoryBreakdown,
    overallScore: clampScore(overallScore, 0, 100),
    interviewReadinessScore,
    recruiterAttentionScore,
    interviewReadinessLevel: readinessLevel(interviewReadinessScore),
    overallConfidence: clampScore(report.overallConfidence, 0, 100),
    atsConfidence: clampScore(report.atsConfidence, 0, 100),
    clarityConfidence: clampScore(report.clarityConfidence, 0, 100),
    impactConfidence: clampScore(report.impactConfidence, 0, 100),
    keywordConfidence: clampScore(report.keywordConfidence, 0, 100),
    presentationConfidence: clampScore(report.presentationConfidence, 0, 100),
    triggeredRules: report.triggeredRules.slice(0, 20),
    precheckTriggeredRules: report.precheckTriggeredRules.slice(0, 20),
    ...categoryScores,
    topIssues: report.topIssues.slice(0, 3),
    finalActionPlan: report.finalActionPlan.slice(0, 8)
  };

  normalized.freePreview = buildFreePreview(normalized);
  normalized.paidReport = buildPaidReport(normalized);

  return normalized;
}

function normalizeCategoryBreakdown(categoryBreakdown: ResumeCategoryBreakdown): ResumeCategoryBreakdown {
  return Object.fromEntries(
    categoryKeys.map((key) => {
      const item = categoryBreakdown[key];
      const score = clampScore(Math.round(item.score), 0, 20);
      const normalized: CategoryBreakdown = {
        score,
        grade: gradeCategory(score),
        explanation: item.explanation,
        evidenceFromResume: item.evidenceFromResume.slice(0, 4),
        improvementAdvice: item.improvementAdvice.slice(0, 4)
      };
      return [key, normalized];
    })
  ) as ResumeCategoryBreakdown;
}

function calibrateCategoryBreakdown(categoryBreakdown: ResumeCategoryBreakdown, report: ResumeReport) {
  const summary = report.precheckSummary;
  const anchors: Record<ScoringCategoryKey, number> = {
    atsCompatibility:
      9 +
      Number(summary.hasExperienceSection) +
      Number(summary.hasEducationSection) +
      Number(summary.hasSkillsSection) * 2 +
      Number(summary.datePatternCount > 0) +
      Number(summary.estimatedBulletCount >= 3) * 2 +
      Number(summary.extractionQualityWarnings.length === 0) * 2 +
      Number(summary.hasEmail || summary.hasPhone),
    clarityStructure:
      7 +
      Number(summary.hasSummarySection) * 2 +
      Number(summary.hasExperienceSection) * 2 +
      Number(summary.hasEducationSection) +
      Number(summary.hasSkillsSection) +
      Math.min(2, Math.floor(summary.estimatedBulletCount / 3)) +
      Math.min(2, summary.roleFocusSignalCount) +
      Number(summary.actionVerbCount >= 3),
    impactAchievements:
      5 +
      Math.min(8, summary.quantifiedBulletCount * 2) +
      Math.min(3, Math.floor(summary.actionVerbCount / 2)) +
      Math.min(2, summary.ownershipSignalCount) +
      Math.min(2, summary.businessImpactSignalCount) -
      Math.min(3, summary.weakPhraseCount),
    keywordRelevance:
      8 +
      Number(summary.hasSkillsSection) * 3 +
      Math.min(4, summary.technicalSignalCount) +
      Math.min(3, summary.roleFocusSignalCount) +
      Number(summary.businessImpactSignalCount > 0),
    professionalPresentation:
      9 +
      Number(summary.hasSummarySection) +
      Number(summary.hasExperienceSection) +
      Number(summary.hasEducationSection) +
      Number(summary.hasSkillsSection) +
      Number(summary.estimatedBulletCount >= 3) * 2 +
      Number(summary.extractionQualityWarnings.length === 0) * 2 +
      Number(summary.actionVerbCount >= 3) -
      Math.min(2, summary.weakPhraseCount)
  };

  return Object.fromEntries(
    categoryKeys.map((key) => {
      const score = clampScore(Math.round(categoryBreakdown[key].score * 0.15 + anchors[key] * 0.85), 0, 20);
      return [key, { ...categoryBreakdown[key], score, grade: gradeCategory(score) }];
    })
  ) as ResumeCategoryBreakdown;
}

function buildPrecheckAwareTopIssues(report: ResumeReport) {
  const highImpactIssues: string[] = [];
  const secondaryIssues: string[] = [];
  const summary = report.precheckSummary;

  if (!summary.hasExperienceSection) {
    highImpactIssues.push("Your experience is not grouped under a recognizable heading, so recruiters may struggle to find your evidence quickly; use a standard Experience heading and a consistent role-date-bullet structure.");
  }
  if (summary.quantifiedBulletCount === 0) {
    highImpactIssues.push("Your experience describes activity without enough evidence of scale or results, which makes your contribution difficult to compare; add truthful volume, time, quality, revenue, user, or delivery context to the strongest bullets.");
  }
  if (!summary.hasSkillsSection) {
    highImpactIssues.push("Your role-specific capabilities are not consolidated in a skills section, reducing fast recruiter and ATS recognition; add a focused list of tools and functional skills supported elsewhere in the resume.");
  }
  if (summary.roleFocusSignalCount === 0) {
    highImpactIssues.push("The target role is difficult to infer in the first scan, which weakens recruiter confidence; name one role direction in the summary and align the first experience bullets to it.");
  }
  if (summary.weakPhraseCount >= 2) {
    highImpactIssues.push("Several bullets lead with passive responsibility language, which hides ownership; replace those openings with the specific action you took and the result or scope of the work.");
  }
  if (summary.extractionQualityWarnings.length > 0) {
    secondaryIssues.push("Some resume text did not extract cleanly, which may hide otherwise strong evidence; export a simple text-based DOCX or PDF and confirm headings and bullets remain readable.");
  }
  if (!summary.hasEmail && !summary.hasPhone) {
    secondaryIssues.push("No direct contact channel was detected; add one professional email and phone number in the document body so a recruiter can act on a positive review.");
  }

  const modelIssues = report.topIssues
    .filter((issue) => !(summary.quantifiedBulletCount >= 3 && issueTopic(issue) === "evidence"))
    .filter((issue) => !(summary.roleFocusSignalCount >= 2 && issueTopic(issue) === "role"))
    .filter(
      (issue) =>
        !(
          summary.estimatedBulletCount >= 4 &&
          summary.wordCount >= 80 &&
          /\b(short|brief|word count|only \d+ words)\b/i.test(issue)
        )
    );
  const candidates = [...highImpactIssues, ...modelIssues, ...secondaryIssues].map(ensureActionableIssue);
  return uniqueIssues(candidates).slice(0, 3);
}

function uniqueIssues(issues: string[]) {
  const unique: string[] = [];

  for (const issue of issues.map((item) => item.trim()).filter(Boolean)) {
    const topic = issueTopic(issue);
    const normalized = issue
      .toLowerCase()
      .replace(/\b(email|phone|linkedin|contact information|contact details)\b/g, "contact")
      .replace(/[^a-z0-9 ]/g, " ")
      .replace(/\s+/g, " ");
    const words = new Set(normalized.split(" ").filter((word) => word.length > 3));
    const duplicate = unique.some((existing) => {
      if (topic && issueTopic(existing) === topic) return true;
      const existingWords = new Set(
        existing.toLowerCase().replace(/[^a-z0-9 ]/g, " ").split(/\s+/).filter((word) => word.length > 3)
      );
      const overlap = [...words].filter((word) => existingWords.has(word)).length;
      return overlap >= Math.min(4, Math.max(2, Math.floor(words.size * 0.45)));
    });
    if (!duplicate) unique.push(issue);
  }

  const fallbacks = [
    "The resume would benefit from a clearer target-role story; connect the summary, skills, and first experience entry around the same direction.",
    "The strongest evidence is not consistently placed first; lead each role with the result that best demonstrates readiness for the target work.",
    "Some capabilities appear as claims rather than demonstrated experience; connect the most important skills to a specific project, action, or outcome."
  ];
  for (const fallback of fallbacks) {
    if (unique.length >= 3) break;
    const topic = issueTopic(fallback);
    if (topic && unique.some((issue) => issueTopic(issue) === topic)) continue;
    unique.push(fallback);
  }
  return unique;
}

function issueTopic(issue: string) {
  const lower = issue.toLowerCase();
  if (/\b(email|phone|linkedin|contact)\b/.test(lower)) return "contact";
  if (/\b(metric|quantif|scale|result|achievement|impact)\b/.test(lower)) return "evidence";
  if (/\b(skills?|capabilit(?:y|ies)|tools?)\b/.test(lower)) return "skills";
  if (/\b(target role|role direction|role-specific|role focus)\b/.test(lower)) return "role";
  if (/\b(responsib|passive|action verb|ownership)\b/.test(lower)) return "ownership";
  if (/\b(extract|parse|file format)\b/.test(lower)) return "extraction";
  return "";
}

function ensureActionableIssue(issue: string) {
  if (
    /\b(add|rewrite|replace|clarify|move|name|connect|group|remove|expand|prioritize|lead|include|define|quantify|revise|refine|align|incorporate|highlight|research|specify|provide|use)\b/i.test(
      issue
    )
  ) {
    return issue;
  }

  switch (issueTopic(issue)) {
    case "contact":
      return `${issue.replace(/[.\s]+$/, "")}; add one professional email and phone number in the document body.`;
    case "evidence":
      return `${issue.replace(/[.\s]+$/, "")}; rewrite the first two experience bullets to show the action, scope, and result.`;
    case "skills":
      return `${issue.replace(/[.\s]+$/, "")}; add a focused skills section and connect its most important capabilities to experience evidence.`;
    case "role":
      return `${issue.replace(/[.\s]+$/, "")}; name one target role in the summary and align the first three bullets to that direction.`;
    case "ownership":
      return `${issue.replace(/[.\s]+$/, "")}; replace passive openings with the specific decision, action, or improvement you owned.`;
    default:
      return `${issue.replace(/[.\s]+$/, "")}; revise the relevant section with one concrete example that resolves this uncertainty.`;
  }
}

function readinessLevel(score: number): ResumeReport["interviewReadinessLevel"] {
  if (score >= 76) return "High";
  if (score >= 56) return "Medium";
  return "Low";
}

function buildResumeEnginePreCheck(report: ResumeReport) {
  const summary = report.precheckSummary;

  return {
    contactCompleteness: [
      summary.hasEmail ? "email found" : "email missing",
      summary.hasPhone ? "phone found" : "phone missing",
      summary.hasLinkedIn ? "LinkedIn found" : "LinkedIn missing"
    ].join(", "),
    sectionCompleteness: [
      summary.hasExperienceSection ? "experience found" : "experience missing",
      summary.hasSkillsSection ? "skills found" : "skills missing"
    ].join(", "),
    quantifiedAchievements:
      summary.quantifiedBulletCount > 0
        ? `${summary.quantifiedBulletCount} quantified achievement bullet(s) detected.`
        : "No quantified achievement bullets detected.",
    weakPhrases:
      summary.weakPhraseCount > 0
        ? `${summary.weakPhraseCount} weak phrase(s) detected.`
        : "No common weak phrases detected.",
    extractionQualityWarnings: summary.extractionQualityWarnings
  };
}

function buildTop10Priorities(report: ResumeReport) {
  const fromRecommendations = report.fiveMostImportantChanges.flatMap((item) => [
    item.whatToChangeNext,
    item.whatWeNoticed
  ]);
  const combined = [...fromRecommendations, ...report.finalActionPlan, ...report.weaknesses];
  const unique = Array.from(new Set(combined.map((item) => item.trim()).filter(Boolean)));

  while (unique.length < 10) {
    unique.push("Choose one target job posting and update the summary, skills, and first three bullets to match its required responsibilities and tools.");
  }

  return unique.slice(0, 10);
}

function clampScore(value: number, min: number, max: number) {
  if (Number.isNaN(value)) return min;
  return Math.max(min, Math.min(max, value));
}
