export const engineName = "Resume Engine";
export const engineVersion = "1.2.0";
export const engineLanguage = "English";
export const engineMarket = "US / UK / Canada / Australia style resumes";

export const generatedBy = `Generated by ${engineName} v${engineVersion}`;
