import { gradeCategory } from "./resumeRules";
import {
  CategoryBreakdown,
  ResumeCategoryBreakdown,
  ResumeFreePreview,
  ResumePaidReport,
  ResumeReport,
  ScoringCategoryKey
} from "./resumeTypes";
import { engineVersion } from "./resumeVersion";

const categoryKeys: ScoringCategoryKey[] = [
  "atsCompatibility",
  "clarityStructure",
  "impactAchievements",
  "keywordRelevance",
  "professionalPresentation"
];

export function buildFreePreview(report: ResumeReport): ResumeFreePreview {
  return {
    overallScore: Math.round(report.overallScore),
    atsReadinessScore: Math.round(report.atsCompatibilityScore),
    interviewReadinessLevel: report.interviewReadinessLevel,
    top3Issues: buildPrecheckAwareTopIssues(report)
  };
}

export function buildPaidReport(report: ResumeReport): ResumePaidReport {
  return {
    categoryBreakdown: report.categoryBreakdown,
    detailedExplanation: report.summaryDiagnosis,
    sectionFeedback: report.sectionFeedback,
    top10ImprovementPriorities: buildTop10Priorities(report),
    missingKeywords: report.missingKeywords,
    rewriteExamples: report.rewriteExamples,
    finalActionPlan: report.finalActionPlan,
    triggeredRules: report.triggeredRules,
    resumeEnginePreCheck: buildResumeEnginePreCheck(report)
  };
}

export function buildDownloadableReportData(report: ResumeReport) {
  return {
    engineVersion: report.engineVersion,
    generatedBy: `Generated by Resume Engine v${report.engineVersion}`,
    freePreview: report.freePreview,
    paidReport: report.paidReport,
    disclaimer: report.disclaimer
  };
}

export function normalizeResumeReport(report: ResumeReport): ResumeReport {
  const categoryBreakdown = applyPrecheckScoreCaps(normalizeCategoryBreakdown(report.categoryBreakdown), report);
  const categoryScores = {
    atsCompatibilityScore: categoryBreakdown.atsCompatibility.score * 5,
    clarityStructureScore: categoryBreakdown.clarityStructure.score * 5,
    impactAchievementsScore: categoryBreakdown.impactAchievements.score * 5,
    keywordRelevanceScore: categoryBreakdown.keywordRelevance.score * 5,
    professionalPresentationScore: categoryBreakdown.professionalPresentation.score * 5
  };
  const overallScore = categoryKeys.reduce((sum, key) => sum + categoryBreakdown[key].score, 0);

  const normalized: ResumeReport = {
    ...report,
    engineVersion,
    categoryBreakdown,
    overallScore: clampScore(overallScore, 0, 100),
    overallConfidence: clampScore(report.overallConfidence, 0, 100),
    atsConfidence: clampScore(report.atsConfidence, 0, 100),
    clarityConfidence: clampScore(report.clarityConfidence, 0, 100),
    impactConfidence: clampScore(report.impactConfidence, 0, 100),
    keywordConfidence: clampScore(report.keywordConfidence, 0, 100),
    presentationConfidence: clampScore(report.presentationConfidence, 0, 100),
    triggeredRules: report.triggeredRules.slice(0, 20),
    precheckTriggeredRules: report.precheckTriggeredRules.slice(0, 20),
    ...categoryScores,
    topIssues: report.topIssues.slice(0, 3),
    finalActionPlan: report.finalActionPlan.slice(0, 8)
  };

  normalized.freePreview = buildFreePreview(normalized);
  normalized.paidReport = buildPaidReport(normalized);

  return normalized;
}

function normalizeCategoryBreakdown(categoryBreakdown: ResumeCategoryBreakdown): ResumeCategoryBreakdown {
  return Object.fromEntries(
    categoryKeys.map((key) => {
      const item = categoryBreakdown[key];
      const score = clampScore(Math.round(item.score), 0, 20);
      const normalized: CategoryBreakdown = {
        score,
        grade: gradeCategory(score),
        explanation: item.explanation,
        evidenceFromResume: item.evidenceFromResume.slice(0, 4),
        improvementAdvice: item.improvementAdvice.slice(0, 4)
      };
      return [key, normalized];
    })
  ) as ResumeCategoryBreakdown;
}

function applyPrecheckScoreCaps(categoryBreakdown: ResumeCategoryBreakdown, report: ResumeReport) {
  const updated = { ...categoryBreakdown };
  const summary = report.precheckSummary;

  if (!summary.hasEmail) updated.atsCompatibility = capCategory(updated.atsCompatibility, 16);
  if (!summary.hasExperienceSection) updated.clarityStructure = capCategory(updated.clarityStructure, 14);
  if (summary.quantifiedBulletCount === 0) updated.impactAchievements = capCategory(updated.impactAchievements, 13);

  return updated;
}

function capCategory(category: CategoryBreakdown, maxScore: number): CategoryBreakdown {
  const score = Math.min(category.score, maxScore);

  return {
    ...category,
    score,
    grade: gradeCategory(score)
  };
}

function buildPrecheckAwareTopIssues(report: ResumeReport) {
  const issues: string[] = [];
  const summary = report.precheckSummary;

  if (!summary.hasEmail) issues.push("Your resume appears to be missing an email address.");
  if (!summary.hasExperienceSection) issues.push("No clear work experience section was detected.");
  if (!summary.hasSkillsSection) issues.push("No clear skills section was detected.");
  if (summary.quantifiedBulletCount === 0) issues.push("No quantified achievements were detected.");
  if (summary.weakPhraseCount >= 2) issues.push("Several weak phrases may make your impact sound less specific.");
  if (summary.extractionQualityWarnings.length > 0) issues.push("The uploaded file may have text extraction quality issues.");

  return [...issues, ...report.topIssues].slice(0, 3);
}

function buildResumeEnginePreCheck(report: ResumeReport) {
  const summary = report.precheckSummary;

  return {
    contactCompleteness: [
      summary.hasEmail ? "email found" : "email missing",
      summary.hasPhone ? "phone found" : "phone missing",
      summary.hasLinkedIn ? "LinkedIn found" : "LinkedIn missing"
    ].join(", "),
    sectionCompleteness: [
      summary.hasExperienceSection ? "experience found" : "experience missing",
      summary.hasSkillsSection ? "skills found" : "skills missing"
    ].join(", "),
    quantifiedAchievements:
      summary.quantifiedBulletCount > 0
        ? `${summary.quantifiedBulletCount} quantified achievement bullet(s) detected.`
        : "No quantified achievement bullets detected.",
    weakPhrases:
      summary.weakPhraseCount > 0
        ? `${summary.weakPhraseCount} weak phrase(s) detected.`
        : "No common weak phrases detected.",
    extractionQualityWarnings: summary.extractionQualityWarnings
  };
}

function buildTop10Priorities(report: ResumeReport) {
  const fromRecommendations = report.fiveMostImportantChanges.flatMap((item) => [
    item.whatToChangeNext,
    item.whatWeNoticed
  ]);
  const combined = [...fromRecommendations, ...report.finalActionPlan, ...report.weaknesses];
  const unique = Array.from(new Set(combined.map((item) => item.trim()).filter(Boolean)));

  while (unique.length < 10) {
    unique.push("Choose one target job posting and update the summary, skills, and first three bullets to match its required responsibilities and tools.");
  }

  return unique.slice(0, 10);
}

function clampScore(value: number, min: number, max: number) {
  if (Number.isNaN(value)) return min;
  return Math.max(min, Math.min(max, value));
}
